name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        # Docs: https://docs.github.com/en/actions/using-containerized-services
        services:
          mysql:
            image: mysql:latest
            env:
              MYSQL_ALLOW_EMPTY_PASSWORD: true
              MYSQL_ROOT_PASSWORD:
              MYSQL_DATABASE: flow_testing
            ports:
              - 3306/tcp
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

          # redis:
          #   image: redis
          #   ports:
          #     - 6379/tcp
          #   options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.2]
                laravel: [9.*, 10.*]
                stability: [prefer-stable]
                include:
                  - laravel: 10.*
                    testbench: ^8.0
                  - laravel: 9.*
                    testbench: ^7.0

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/pest
